<?php


namespace HackLog\Model;


class Post extends Taggable
{
    private $title;
    private $urlTitle;
    private $content;
    private $blog;
    private $tags;
    private $visibility;
    private $publishedAt;
    private $comments;

    public function bsonSerialize()
    {
        $serial = parent::bsonSerialize();
        $serial = array_merge(
            $serial, [
            'title' => $this->title,
            'urlTitle' => $this->urlTitle,
            'content' => $this->content,
            'blog' => $this->blog,
            'tags' => $this->tags,
            'visibility' => $this->visibility,
            'publishedAt' => $this->publishedAt,
            'comments' => $this->comments,
            ]
        );
        return  $serial;// TODO: Change the autogenerated stub
    }

    public function bsonUnserialize(array $data)
    {
        parent::bsonUnserialize($data); // TODO: Change the autogenerated stub
        $this->title = $data['title'];
        $this->urlTitle = $data['urlTitle'];
        $this->content = $data['content'];
        $this->blog = $data['blog'];
        $this->tags = $data['tags'];
        $this->visibility = $data['visibility'];
        $this->publishedAt = $data['publishedAt'];
        $this->comments = $data['comments'];
    }
}

