<?php


namespace HackLog\Model;

use HackLog\Core\Model;

class TaggableModel extends Model
{
    protected $tags = [];

    public function bsonSerialize()
    {
        $serial = parent::bsonSerialize();
        $serial['tags'] = $this->tags;
        return $serial;// TODO: Change the autogenerated stub
    }

    public function bsonUnserialize(array $data)
    {
        $this->tags = $data['tags'];
        parent::bsonUnserialize($data); // TODO: Change the autogenerated stub
    }
}
