language: php
php:
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-nightly



matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: 7.1
        - php: nightly
        - php: hhvm-nightly


before_script:
  - composer self-update

before_install:
  - echo "extension mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  
install:
  - composer install

script:
  - vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 app