language: php

php:
  - 7.0
  - 7.1
  - nightly
  #- hhvm
  #- hhvm-3.3
  #- hhvm-3.6
  #- hhvm-3.9
  #- hhvm-3.12

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
  - sudo echo 'extension= "mongodb.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

before_script:
  - composer self-update

script:
  # - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 app