<?php


namespace HackLog\Document;


class PostDocument extends TaggableDocument
{
    private $title;
    private $urlTitle;
    private $content;
    private $blog;
    private $tags;
    private $visibility;
    private $publishedAt;
    private $language;
    private $comments;

    public function bsonSerialize()
    {
        $serial = parent::bsonSerialize();
        $serial = array_merge(
            $serial,
            [
                'title' => $this->title,
                'urlTitle' => $this->urlTitle,
                'content' => $this->content,
                'blog' => $this->blog,
                'tags' => $this->tags,
                'visibility' => $this->visibility,
                'publishedAt' => $this->publishedAt,
                'language' => $this->language,
                'comments' => $this->comments,
            ]
        );
        return $serial;// TODO: Change the autogenerated stub
    }

    public function bsonUnserialize(array $data)
    {
        parent::bsonUnserialize($data); // TODO: Change the autogenerated stub
        $this->title = $data['title'];
        $this->urlTitle = $data['urlTitle'];
        $this->content = $data['content'];
        $this->blog = $data['blog'];
        $this->tags = $data['tags'];
        $this->visibility = $data['visibility'];
        $this->publishedAt = $data['publishedAt'];
        $this->language = $data['language'];
        $this->comments = $data['comments'];
    }
}
